<?xml version="1.0" encoding="utf-8"?><Database Name="rail" Class="railDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\rail.mdf;Integrated Security=True" SettingsObjectName="RailwaySystem.My.MySettings" SettingsPropertyName="railConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Booking" Member="Bookings">
    <Type Name="Booking">
      <Column Name="bookingID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="source" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="destination" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="departureTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="custID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="scheduleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="departureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="seatType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Booking_Payment" Member="Payments" ThisKey="bookingID" OtherKey="bookingID" Type="Payment" />
      <Association Name="Customer_Booking" Member="Customer" ThisKey="custID" OtherKey="custID" Type="Customer" IsForeignKey="true" />
      <Association Name="Schedule_Booking" Member="Schedule" ThisKey="scheduleID" OtherKey="scheduleID" Type="Schedule" IsForeignKey="true" />
      <Association Name="Station_Booking" Member="Station" ThisKey="destination" OtherKey="stationID" Type="Station" IsForeignKey="true" />
      <Association Name="Station_Booking1" Member="Station1" ThisKey="source" OtherKey="stationID" Type="Station" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Card" Member="Cards">
    <Type Name="Card">
      <Column Name="cardNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cardHolderName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cardType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="expiryMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="expiryYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ccv" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="issuer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="balance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Card_Payment" Member="Payments" ThisKey="cardNo" OtherKey="cardNo" Type="Payment" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="custID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="custName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="custIC" Type="System.String" DbType="Char(13)" CanBeNull="true" />
      <Column Name="custPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="custEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="custAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="custType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="custPassword" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Customer_Booking" Member="Bookings" ThisKey="custID" OtherKey="custID" Type="Booking" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="scheduleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="startTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="endTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="firstStationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastStationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Schedule_Booking" Member="Bookings" ThisKey="scheduleID" OtherKey="scheduleID" Type="Booking" />
      <Association Name="Station_Schedule" Member="Station" ThisKey="firstStationID" OtherKey="stationID" Type="Station" IsForeignKey="true" />
      <Association Name="Station_Schedule1" Member="Station1" ThisKey="lastStationID" OtherKey="stationID" Type="Station" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="paymentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="paymentDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="paymentTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="cardNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="staffInCharge" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bookingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Booking_Payment" Member="Booking" ThisKey="bookingID" OtherKey="bookingID" Type="Booking" IsForeignKey="true" />
      <Association Name="Card_Payment" Member="Card" ThisKey="cardNo" OtherKey="cardNo" Type="Card" IsForeignKey="true" />
      <Association Name="Staff_Payment" Member="Staff" ThisKey="staffInCharge" OtherKey="staffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="staffID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="staffName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="staffIC" Type="System.String" DbType="Char(13)" CanBeNull="true" />
      <Column Name="staffPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="staffAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="staffEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Staff_Payment" Member="Payments" ThisKey="staffID" OtherKey="staffInCharge" Type="Payment" />
    </Type>
  </Table>
  <Table Name="dbo.Station" Member="Stations">
    <Type Name="Station">
      <Column Name="stationID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Station_Booking" Member="Bookings" ThisKey="stationID" OtherKey="destination" Type="Booking" />
      <Association Name="Station_Booking1" Member="Bookings1" ThisKey="stationID" OtherKey="source" Type="Booking" />
      <Association Name="Station_Schedule" Member="Schedules" ThisKey="stationID" OtherKey="firstStationID" Type="Schedule" />
      <Association Name="Station_Schedule1" Member="Schedules1" ThisKey="stationID" OtherKey="lastStationID" Type="Schedule" />
    </Type>
  </Table>
</Database>